name: Release Charts

on:
  push:
    branches:
      - main
    tags: ["v*"]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3.1
        with:
          version: v3.4.1

      - name: Add dependent repositories
        run: |
          helm repo add open-telemetry https://open-telemetry.github.io/opentelemetry-helm-charts
          helm repo add bitnami https://charts.bitnami.com/bitnami    
          helm repo add redis https://ot-container-kit.github.io/helm-charts
          helm dep up charts/openinsight
          helm dep up charts/opentelemetry-demo

      - name: Release Helm Chart
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.ACTIONS_TOKEN }}"
          
#       - name: Add DaoCloud Registry
#         env:
#           DAOCLOUD_COMMUNITY_REGISTRY_URL: release.daocloud.io
#           HELM_EXPERIMENTAL_OCI: 1
#         run: |
#           helm registry login $DAOCLOUD_COMMUNITY_REGISTRY_URL --username ${{ secrets.DAOCLOUD_REGISTRY_USERNAME }} --password ${{ secrets.DAOCLOUD_REGISTRY_PASSWORD }}

#       - name: Release to DaoCloud Community Chart Repo
#         uses: helm/chart-releaser-action@v1.5.0
#         env:
#           CR_TOKEN: "${{ secrets.ACTIONS_TOKEN }}"
#         with:
#           charts_repo_url: $DAOCLOUD_COMMUNITY_REGISTRY_URL

